# Generated by Django 5.0.7 on 2024-07-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerpApiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.IntegerField()),
                ('website_link', models.URLField()),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('serp_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.serpapiresult')),
            ],
        ),
        migrations.AddField(
            model_name='serpapiresult',
            name='uploaded_excel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.uploadedexcel'),
        ),
    ]
